[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = " default-src 'none'; font-src 'self' https://fonts.gstatic.com https://kit-free.fontawesome.com; img-src https://deepline.gumlet.com https://deeplineproject.com; script-src 'self' 'unsafe-inline' https://cdn.gumlet.com/gumlet.js/2.0/gumlet.min.js https://cdn.rawgit.com/noelboss/featherlight/1.3.5/release/featherlight.min.js https://deeplineproject.disqus.com/count.js https://kit.fontawesome.com/7421e320e6.js https://www.google-analytics.com/analytics.js https://www.googletagmanager.com/gtag/js; style-src 'self' https://cdn.rawgit.com/noelboss/featherlight/1.3.5/release/ https://fonts.googleapis.com/ https://kit-free.fontawesome.com/releases/latest/css/ "
