# Header
menu:
  Log: /
  Tracking: /Track
  Posts by Name: /archives
  Posts by Location: /mapofposts
  # Meteo: /tags/meteo
  Ayvri: "https://ayvri.com/profile/g0jgg3yejo"
  XContest: "https://www.xcontest.org/world/en/pilots/detail:jalexs"
  Leonardo: "https://www.paraglidingforum.com/leonardo/pilot/0_74191"


# Default
default_post_title: Untitled
default_post_subtitle: Unknown
default_cover_detail: https://deeplineproject.com/2019/03/02/Ager/launch.jpg
default_cover_index: https://deeplineproject.com/2019/03/02/Ager/launch_cover.jpg

# Favicon
favicon: https://deepline.gumlet.com/2018/12/30/Valle/favicon.ico

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: deeplineproject

# Google Analytics Tracking ID
google_analytics: UA-160778123-1

# Social Accounts
twitter_url:
facebook_url:
behance_url:
googleplus_url:
dribble_url:
rss_url:
instagram_url:
youtube_url:
